package kr.co.himedia.String;

public class StringTextBlockTest {
	
	public static void main(String[] args) {
		
		String textBlock = """
				This
				is
				text
				block
				""";
		
		
		System.out.println(textBlock);
		
		System.out.println();
		
		System.out.println(getHtmlBlock());
		
	}
	
	public static String getHtmlBlock() {
		return """
				<html lang="en">
<head>
<!-- Generated by javadoc (20) -->
<title>StringBuffer (Java SE 20 &amp; JDK 20)</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="description" content="declaration: module: java.base, package: java.lang, class: StringBuffer">
<meta name="generator" content="javadoc/ClassWriterImpl">
<meta name="keywords" content="java.lang.StringBuffer class">
<meta name="keywords" content="compareTo()">
<meta name="keywords" content="length()">
<meta name="keywords" content="capacity()">
<meta name="keywords" content="ensureCapacity()">
<meta name="keywords" content="trimToSize()">
<meta name="keywords" content="setLength()">
<meta name="keywords" content="charAt()">
<meta name="keywords" content="codePointAt()">
<meta name="keywords" content="codePointBefore()">
<meta name="keywords" content="codePointCount()">
<meta name="keywords" content="offsetByCodePoints()">
<meta name="keywords" content="getChars()">
<meta name="keywords" content="setCharAt()">
<meta name="keywords" content="append()">
<meta name="keywords" content="appendCodePoint()">
<meta name="keywords" content="delete()">
<meta name="keywords" content="deleteCharAt()">
<meta name="keywords" content="replace()">
<meta name="keywords" content="substring()">
<meta name="keywords" content="subSequence()">
<meta name="keywords" content="insert()">
<meta name="keywords" content="indexOf()">
<meta name="keywords" content="lastIndexOf()">
<meta name="keywords" content="reverse()">
<meta name="keywords" content="toString()">
<link rel="stylesheet" type="text/css" href="../../../stylesheet.css" title="Style">
<link rel="stylesheet" type="text/css" href="../../../script-dir/jquery-ui.min.css" title="Style">
<script type="text/javascript" src="../../../script.js"></script>
<script type="text/javascript" src="../../../script-dir/jquery-3.6.1.min.js"></script>
<script type="text/javascript" src="../../../script-dir/jquery-ui.min.js"></script>
</head>
<body class="class-declaration-page">
<script type="text/javascript">var pathtoroot = "../../../";
loadScripts(document, 'script');</script>
<noscript>
<div>JavaScript is disabled on your browser.</div>
</noscript>
				""";
	}
	

}
